# Configuración de Foot Terminal

# Fuente y tipografía
font=FreeMono:size=11
# font-bold=JetBrainsMono Nerd Font:size=11:style=Bold

[environment]
# Puedes definir variables de entorno aquí si lo necesitas

[bell]
urgent=yes
notify=no

[scrollback]
lines=10000
multiplier=3.0

[cursor]
style=block
blink=yes

[mouse]
hide-when-typing=yes

[colors-dark]
background=040300
foreground=f4e5ae

## Normal / Dim Colors (ANSI 0-7)
regular0=110d00  # surfaceBright
regular1=fe7453  # error (Red)
regular2=ffeeaa  # primary (Green/Gold alternative)
regular3=f5e085  # primaryDim (Yellow)
regular4=cabeff  # tertiary (Blue)
regular5=bcaeff  # tertiaryContainer (Magenta)
regular6=cbc2db  # secondary (Cyan)
regular7=b8ab79  # onSurfaceVariant (White)

## Bright Colors (ANSI 8-15)
bright0=51481f    # outlineVariant
bright1=c74c2f    # errorDim
bright2=f5e085
bright3=e6d279    # primaryFixedDim
bright4=bcaeff
bright5=ae9ffa    # tertiaryDim
bright6=eee4fe    # secondaryFixed
bright7=fff9ed    # inverseSurface

## UI Selection / Miscellaneous 
selection-foreground=040300
selection-background=ffeeaa
urls=cabeff

alpha=0.8
